config/routes.rb
Rails.application.routes.draw do

  devise_for :clients
  root 'pages#index', as: 'home'
  
  get 'about' => 'pages#about', as: 'about'
  
  get 'blog' => 'pages#blog', as: 'blog'
  
  get 'services' => 'pages#services', as: 'services'
  
  get 'contact' => 'pages#contact', as: 'contact'

end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def services
  end

  def contact
  end

  def about
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnandROR</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/nav' %>
<%= bootstrap_flash %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/blog.html.erb
<h1>Blog</h1>

app/views/pages/contact.html.erb
<h1>Contact Us </h1>

app/views/pages/services.html.erb
<h1>Services</h1>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Anand</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home",home_path,class:"nav-link"  %>
          </li>
          <li class="nav-item active">
            <%= link_to "Services",services_path,class:"nav-link"  %>
          </li>
          <li class="nav-item active">
            <%= link_to "Blog",blog_path,class:"nav-link"  %>
          </li>
          <li class="nav-item active">
            <%= link_to "Contact Us",contact_path,class:"nav-link"  %>
          </li>
          <li class="nav-item active">
            <%= link_to "About Us",about_path,class:"nav-link"  %>
          </li>
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign Up",new_client_registration_path %></li>
            <li><%= link_to "Login",new_client_session_path %></li>
            <li><%= link_to "Sign Out",destroy_client_session_path , method: :delete %></li>
          </ul>
      </div>
    </nav>